[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizerSteps = ''
optimizer = true
optimizer_runs = 200
#solc = "0.8.26"
# remappings = [
#     "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
#     "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
#     "@uniswap/v3-core/=lib/v3-core/",
#     "@uniswap/v3-periphery/=lib/v3-periphery/",
#     "@uniswap/v2-core/=lib/v2-core/",
#     "@uniswap/v2-periphery/=lib/v2-periphery/",
#     "@uniswap/swap-router/=lib/swap-router-contracts/contracts/",
#     "forge-std/=lib/forge-std/src/",
#     "src/=src/",
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
